version: '3'
services:
  hello-world:
    build: ./microservices/hello-world-server
    image: hello-world-service
    environment:
      - HELLO_MESSAGE="Hello World! (hello-world-service)"
      - PORT=8081
    ports:
      - "8081:8081"
